// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  tseslint.configs.strict,
  tseslint.configs.stylistic,
  {
    ignores: ['dist', 'node_modules', 'coverage'],
  },
  {
    files: ['src/types/db.ts'], // this file is automatically generated, so i'm disabling a rule that the generator doesn't follow
    rules: {
      '@typescript-eslint/consistent-type-definitions': 'off',
    },
  }
);
