/*
 * This file was generated by kysely-codegen.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export interface JsonObject {
  [x: string]: JsonValue | undefined;
}

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Log {
  context: Json | null;
  environment: string;
  id: string;
  is_handled: Generated<boolean>;
  level: string;
  message: string;
  origin: string;
  project_id: string;
  tags: string[] | null;
  timestamp: Generated<Timestamp>;
}

export interface Project {
  createdAt: Generated<Timestamp>;
  description: string;
  id: string;
  name: string;
  updatedAt: Generated<Timestamp>;
  user_id: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  password_hash: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  log: Log;
  project: Project;
  user: User;
}
