/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type SessionStatus = "active" | "inactive";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Log {
  context: Json | null;
  environment: string;
  id: Generated<string>;
  isHandled: Generated<boolean>;
  level: string;
  message: string;
  origin: string;
  projectId: string;
  tags: string[] | null;
  timestamp: Generated<Timestamp>;
}

export interface Project {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  ownerId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string;
  refreshToken: string;
  status: Generated<SessionStatus>;
  updatedAt: Generated<Timestamp>;
  userAgent: string;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  log: Log;
  project: Project;
  session: Session;
  user: User;
}
